export const SEED_POSITIONS = [
  {
    id: 'seed-pos-1',
    name: 'Front Counter',
    category: 'FOH',
    description: 'Taking orders and serving guests at the front counter',
    sortOrder: 1,
    createdAt: new Date().toISOString(),
  },
  {
    id: 'seed-pos-2',
    name: 'Drive Thru Order',
    category: 'Drive Thru',
    description: 'Taking orders at the drive thru speaker',
    sortOrder: 2,
    createdAt: new Date().toISOString(),
  },
  {
    id: 'seed-pos-3',
    name: 'Drive Thru Window',
    category: 'Drive Thru',
    description: 'Handling payment and serving guests at the window',
    sortOrder: 3,
    createdAt: new Date().toISOString(),
  },
  {
    id: 'seed-pos-4',
    name: 'Breading',
    category: 'BOH',
    description: 'Breading chicken in the kitchen',
    sortOrder: 4,
    createdAt: new Date().toISOString(),
  },
  {
    id: 'seed-pos-5',
    name: 'Sandwich Assembly',
    category: 'BOH',
    description: 'Assembling sandwiches and wraps',
    sortOrder: 5,
    createdAt: new Date().toISOString(),
  },
  {
    id: 'seed-pos-6',
    name: 'Nuggets & Strips',
    category: 'BOH',
    description: 'Cooking and packaging nuggets and strips',
    sortOrder: 6,
    createdAt: new Date().toISOString(),
  },
  {
    id: 'seed-pos-7',
    name: 'Fries',
    category: 'BOH',
    description: 'Managing the fry station',
    sortOrder: 7,
    createdAt: new Date().toISOString(),
  },
  {
    id: 'seed-pos-8',
    name: 'Beverages',
    category: 'FOH',
    description: 'Preparing drinks, milkshakes, and lemonade',
    sortOrder: 8,
    createdAt: new Date().toISOString(),
  },
];
